-- Privacy-conscious subscriptions and page-view analytics for SEED VOICE.
-- Raw subscriber emails are never readable by anon/authenticated roles.

create table if not exists public.newsletter_subscribers (
  email text primary key,
  language text not null default 'ko' check (language in ('ko', 'en')),
  source_path text not null default '/',
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint newsletter_email_length check (char_length(email) between 5 and 254),
  constraint newsletter_source_path_length check (char_length(source_path) between 1 and 300)
);

alter table public.newsletter_subscribers enable row level security;
revoke all on table public.newsletter_subscribers from anon, authenticated;

create table if not exists public.member_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  phone text constraint member_subscription_phone_format check (phone is null or phone ~ '^010-[0-9]{4}-[0-9]{4}$'),
  content_preferences text[] not null constraint member_subscription_preferences check (
    cardinality(content_preferences) > 0
    and content_preferences <@ array['news', 'briefings', 'columns']::text[]
  ),
  social_preferences text[] not null default '{}'::text[] constraint member_subscription_social_preferences check (
    social_preferences <@ array['kakao', 'instagram', 'x', 'telegram']::text[]
  ),
  language text not null default 'ko' check (language in ('ko', 'en')),
  consented_at timestamptz not null,
  verified_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.member_subscriptions
  add column if not exists social_preferences text[] not null default '{}'::text[];

alter table public.member_subscriptions alter column phone drop not null;

do $$ begin
  alter table public.member_subscriptions
    add constraint member_subscription_social_preferences
    check (social_preferences <@ array['kakao', 'instagram', 'x', 'telegram']::text[]);
exception when duplicate_object then null;
end $$;

alter table public.member_subscriptions enable row level security;
revoke all on table public.member_subscriptions from anon, authenticated;

create table if not exists public.content_page_views (
  id bigint generated by default as identity primary key,
  page_path text not null,
  language text not null default 'ko' check (language in ('ko', 'en')),
  referrer_host text,
  viewed_at timestamptz not null default now(),
  constraint page_view_path_length check (char_length(page_path) between 1 and 300),
  constraint page_view_referrer_length check (referrer_host is null or char_length(referrer_host) <= 200)
);

alter table public.content_page_views enable row level security;
revoke all on table public.content_page_views from anon, authenticated;
revoke all on sequence public.content_page_views_id_seq from anon, authenticated;

create index if not exists content_page_views_path_time_idx on public.content_page_views (page_path, viewed_at desc);
create index if not exists content_page_views_time_idx on public.content_page_views (viewed_at desc);

create or replace function public.is_seed_owner()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from auth.users u
    where u.id = auth.uid()
      and u.deleted_at is null
      and u.raw_app_meta_data ->> 'seed_role' = 'owner'
  );
$$;

create or replace function public.subscribe_newsletter(p_email text, p_language text default 'ko', p_source_path text default '/')
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_source_path text := left(coalesce(nullif(p_source_path, ''), '/'), 300);
begin
  if char_length(v_email) < 5 or char_length(v_email) > 254
    or v_email !~* '^[A-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$'
  then raise exception 'invalid email address' using errcode = '22023'; end if;
  if left(v_source_path, 1) <> '/' then v_source_path := '/'; end if;
  insert into public.newsletter_subscribers (email, language, source_path, status, consented_at, updated_at)
  values (v_email, v_language, v_source_path, 'active', now(), now())
  on conflict (email) do update set language = excluded.language, source_path = excluded.source_path,
    status = 'active', consented_at = now(), updated_at = now();
end; $$;

create or replace function public.sync_verified_member_subscription()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  v_phone text := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'contact_phone', '')), '');
  v_preferences text[];
  v_social_preferences text[];
  v_consented_at timestamptz;
begin
  if new.email_confirmed_at is null
    or coalesce(new.raw_user_meta_data ->> 'content_subscription_consent', '') <> 'true'
  then return new; end if;

  select coalesce(array_agg(value), array[]::text[]) into v_preferences
  from jsonb_array_elements_text(coalesce(new.raw_user_meta_data -> 'content_preferences', '[]'::jsonb)) as value
  where value in ('news', 'briefings', 'columns');

  select coalesce(array_agg(value), array[]::text[]) into v_social_preferences
  from jsonb_array_elements_text(coalesce(new.raw_user_meta_data -> 'social_preferences', '[]'::jsonb)) as value
  where value in ('kakao', 'instagram', 'x', 'telegram');

  if (v_phone is not null and v_phone !~ '^010-[0-9]{4}-[0-9]{4}$')
    or ('kakao' = any(v_social_preferences) and v_phone is null)
    or cardinality(v_preferences) = 0
  then return new; end if;

  begin
    v_consented_at := (new.raw_user_meta_data ->> 'content_subscription_consented_at')::timestamptz;
  exception when others then
    v_consented_at := new.email_confirmed_at;
  end;

  insert into public.member_subscriptions (
    user_id, email, phone, content_preferences, social_preferences, language, consented_at, verified_at, updated_at
  ) values (
    new.id, lower(new.email), v_phone, v_preferences, v_social_preferences,
    case when new.raw_user_meta_data ->> 'language' = 'en' then 'en' else 'ko' end,
    coalesce(v_consented_at, new.email_confirmed_at), new.email_confirmed_at, now()
  )
  on conflict (user_id) do update set
    email = excluded.email,
    phone = excluded.phone,
    content_preferences = excluded.content_preferences,
    social_preferences = excluded.social_preferences,
    language = excluded.language,
    consented_at = excluded.consented_at,
    verified_at = excluded.verified_at,
    updated_at = now();

  insert into public.newsletter_subscribers (email, language, source_path, status, consented_at, updated_at)
  values (
    lower(new.email),
    case when new.raw_user_meta_data ->> 'language' = 'en' then 'en' else 'ko' end,
    '/account?mode=signup', 'active', coalesce(v_consented_at, new.email_confirmed_at), now()
  )
  on conflict (email) do update set
    language = excluded.language,
    source_path = excluded.source_path,
    status = 'active',
    consented_at = excluded.consented_at,
    updated_at = now();

  return new;
end; $$;

drop trigger if exists sync_verified_member_subscription_trigger on auth.users;
create trigger sync_verified_member_subscription_trigger
after insert or update of email_confirmed_at, raw_user_meta_data on auth.users
for each row execute function public.sync_verified_member_subscription();

create schema if not exists private;
revoke all on schema private from public;

create or replace function private.cleanup_deleted_member_data()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  delete from public.newsletter_subscribers where lower(email) = lower(old.email);
  return old;
end; $$;

drop trigger if exists cleanup_deleted_member_data_trigger on auth.users;
create trigger cleanup_deleted_member_data_trigger
before delete on auth.users
for each row execute function private.cleanup_deleted_member_data();

revoke all on function public.sync_verified_member_subscription() from public, anon, authenticated;
revoke all on function private.cleanup_deleted_member_data() from public;

create or replace function public.record_content_view(p_path text, p_language text default 'ko', p_referrer_host text default null)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_path text := left(coalesce(nullif(p_path, ''), '/'), 300);
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_referrer text := nullif(left(btrim(coalesce(p_referrer_host, '')), 200), '');
begin
  if left(v_path, 1) <> '/' then v_path := '/'; end if;
  insert into public.content_page_views (page_path, language, referrer_host) values (v_path, v_language, v_referrer);
end; $$;

create or replace function public.get_engagement_summary()
returns table (metric text, value bigint) language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select 'active_subscribers'::text, count(*)::bigint from public.newsletter_subscribers where status = 'active'
    union all select 'all_page_views'::text, count(*)::bigint from public.content_page_views
    union all select 'page_views_7d'::text, count(*)::bigint from public.content_page_views
      where viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul';
end; $$;

create or replace function public.get_content_view_stats()
returns table (page_path text, views bigint, last_viewed_at timestamptz) language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query select v.page_path, count(*)::bigint, max(v.viewed_at) from public.content_page_views v
    group by v.page_path order by count(*) desc, max(v.viewed_at) desc limit 100;
end; $$;

create or replace function public.get_daily_view_stats()
returns table (view_date date, views bigint) language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with days as (
      select generate_series(
        (now() at time zone 'Asia/Seoul')::date - 6,
        (now() at time zone 'Asia/Seoul')::date,
        interval '1 day'
      )::date as day
    ), counts as (
      select (v.viewed_at at time zone 'Asia/Seoul')::date as day, count(*)::bigint as total
      from public.content_page_views v
      where v.viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul'
      group by 1
    )
    select d.day, coalesce(c.total, 0)::bigint
    from days d left join counts c using (day)
    order by d.day;
end; $$;

create or replace function public.get_newsletter_subscribers()
returns table (email text, language text, source_path text, status text, consented_at timestamptz)
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query select s.email, s.language, s.source_path, s.status, s.consented_at
    from public.newsletter_subscribers s order by s.consented_at desc;
end; $$;

drop function if exists public.get_member_registrations();
create function public.get_member_registrations()
returns table (user_id uuid, email text, nickname text, phone text, content_subscription_consent boolean, social_preferences text[], created_at timestamptz, email_confirmed_at timestamptz)
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select u.id, u.email::text,
      coalesce(nullif(btrim(u.raw_user_meta_data ->> 'nickname'), ''), split_part(u.email, '@', 1), '인증회원')::text,
      nullif(btrim(u.raw_user_meta_data ->> 'contact_phone'), '')::text,
      (coalesce(u.raw_user_meta_data ->> 'content_subscription_consent', '') = 'true')::boolean,
      coalesce(
        array(select jsonb_array_elements_text(
          case when jsonb_typeof(u.raw_user_meta_data -> 'social_preferences') = 'array'
            then u.raw_user_meta_data -> 'social_preferences' else '[]'::jsonb end
        )),
        '{}'::text[]
      ),
      u.created_at, u.email_confirmed_at
    from auth.users u
    where u.deleted_at is null
    order by u.created_at desc;
end; $$;

revoke all on function public.subscribe_newsletter(text, text, text) from public, anon, authenticated;
revoke all on function public.record_content_view(text, text, text) from public, anon, authenticated;
revoke all on function public.is_seed_owner() from public, anon, authenticated;
revoke all on function public.get_engagement_summary() from public, anon, authenticated;
revoke all on function public.get_content_view_stats() from public, anon, authenticated;
revoke all on function public.get_daily_view_stats() from public, anon, authenticated;
revoke all on function public.get_newsletter_subscribers() from public, anon, authenticated;
revoke all on function public.get_member_registrations() from public, anon, authenticated;
grant execute on function public.subscribe_newsletter(text, text, text) to anon, authenticated;
grant execute on function public.record_content_view(text, text, text) to anon, authenticated;
grant execute on function public.get_engagement_summary() to authenticated;
grant execute on function public.get_content_view_stats() to authenticated;
grant execute on function public.get_daily_view_stats() to authenticated;
grant execute on function public.get_newsletter_subscribers() to authenticated;
grant execute on function public.get_member_registrations() to authenticated;
