-- Privacy-conscious subscriptions and page-view analytics for SEED VOICE.
-- Raw subscriber emails are never readable by anon/authenticated roles.

create table if not exists public.newsletter_subscribers (
  email text primary key,
  language text not null default 'ko' check (language in ('ko', 'en')),
  source_path text not null default '/',
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint newsletter_email_length check (char_length(email) between 5 and 254),
  constraint newsletter_source_path_length check (char_length(source_path) between 1 and 300)
);

alter table public.newsletter_subscribers enable row level security;
revoke all on table public.newsletter_subscribers from anon, authenticated;

create table if not exists public.content_page_views (
  id bigint generated by default as identity primary key,
  page_path text not null,
  language text not null default 'ko' check (language in ('ko', 'en')),
  referrer_host text,
  viewed_at timestamptz not null default now(),
  constraint page_view_path_length check (char_length(page_path) between 1 and 300),
  constraint page_view_referrer_length check (referrer_host is null or char_length(referrer_host) <= 200)
);

alter table public.content_page_views enable row level security;
revoke all on table public.content_page_views from anon, authenticated;
revoke all on sequence public.content_page_views_id_seq from anon, authenticated;

create index if not exists content_page_views_path_time_idx on public.content_page_views (page_path, viewed_at desc);
create index if not exists content_page_views_time_idx on public.content_page_views (viewed_at desc);

create or replace function public.subscribe_newsletter(p_email text, p_language text default 'ko', p_source_path text default '/')
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_source_path text := left(coalesce(nullif(p_source_path, ''), '/'), 300);
begin
  if char_length(v_email) < 5 or char_length(v_email) > 254
    or v_email !~* '^[A-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?(?:\.[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)+$'
  then raise exception 'invalid email address' using errcode = '22023'; end if;
  if left(v_source_path, 1) <> '/' then v_source_path := '/'; end if;
  insert into public.newsletter_subscribers (email, language, source_path, status, consented_at, updated_at)
  values (v_email, v_language, v_source_path, 'active', now(), now())
  on conflict (email) do update set language = excluded.language, source_path = excluded.source_path,
    status = 'active', consented_at = now(), updated_at = now();
end; $$;

create or replace function public.record_content_view(p_path text, p_language text default 'ko', p_referrer_host text default null)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_path text := left(coalesce(nullif(p_path, ''), '/'), 300);
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_referrer text := nullif(left(btrim(coalesce(p_referrer_host, '')), 200), '');
begin
  if left(v_path, 1) <> '/' then v_path := '/'; end if;
  insert into public.content_page_views (page_path, language, referrer_host) values (v_path, v_language, v_referrer);
end; $$;

create or replace function public.get_engagement_summary()
returns table (metric text, value bigint) language plpgsql security definer set search_path = '' as $$
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'seedcivicpartners@gmail.com' then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select 'active_subscribers'::text, count(*)::bigint from public.newsletter_subscribers where status = 'active'
    union all select 'all_page_views'::text, count(*)::bigint from public.content_page_views
    union all select 'page_views_7d'::text, count(*)::bigint from public.content_page_views
      where viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul';
end; $$;

create or replace function public.get_content_view_stats()
returns table (page_path text, views bigint, last_viewed_at timestamptz) language plpgsql security definer set search_path = '' as $$
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'seedcivicpartners@gmail.com' then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query select v.page_path, count(*)::bigint, max(v.viewed_at) from public.content_page_views v
    group by v.page_path order by count(*) desc, max(v.viewed_at) desc limit 100;
end; $$;

create or replace function public.get_daily_view_stats()
returns table (view_date date, views bigint) language plpgsql security definer set search_path = '' as $$
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'seedcivicpartners@gmail.com' then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with days as (
      select generate_series(
        (now() at time zone 'Asia/Seoul')::date - 6,
        (now() at time zone 'Asia/Seoul')::date,
        interval '1 day'
      )::date as day
    ), counts as (
      select (v.viewed_at at time zone 'Asia/Seoul')::date as day, count(*)::bigint as total
      from public.content_page_views v
      where v.viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul'
      group by 1
    )
    select d.day, coalesce(c.total, 0)::bigint
    from days d left join counts c using (day)
    order by d.day;
end; $$;

create or replace function public.get_newsletter_subscribers()
returns table (email text, language text, source_path text, status text, consented_at timestamptz)
language plpgsql security definer set search_path = '' as $$
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'seedcivicpartners@gmail.com' then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query select s.email, s.language, s.source_path, s.status, s.consented_at
    from public.newsletter_subscribers s order by s.consented_at desc;
end; $$;

revoke all on function public.subscribe_newsletter(text, text, text) from public, anon, authenticated;
revoke all on function public.record_content_view(text, text, text) from public, anon, authenticated;
revoke all on function public.get_engagement_summary() from public, anon, authenticated;
revoke all on function public.get_content_view_stats() from public, anon, authenticated;
revoke all on function public.get_daily_view_stats() from public, anon, authenticated;
revoke all on function public.get_newsletter_subscribers() from public, anon, authenticated;
grant execute on function public.subscribe_newsletter(text, text, text) to anon, authenticated;
grant execute on function public.record_content_view(text, text, text) to anon, authenticated;
grant execute on function public.get_engagement_summary() to authenticated;
grant execute on function public.get_content_view_stats() to authenticated;
grant execute on function public.get_daily_view_stats() to authenticated;
grant execute on function public.get_newsletter_subscribers() to authenticated;
