-- Privacy-first analytics v2 for SEED VOICE.
-- Preserves historical page views while adding anonymous visitor/session,
-- campaign and reading-engagement measurements for new traffic.
-- Raw IP addresses, user agents and personal data are not stored.

alter table public.content_page_views
  add column if not exists visitor_id uuid,
  add column if not exists session_id uuid,
  add column if not exists entry_path text,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists utm_content text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'content_page_views_entry_path_length'
      and conrelid = 'public.content_page_views'::regclass
  ) then
    alter table public.content_page_views
      add constraint content_page_views_entry_path_length
      check (entry_path is null or char_length(entry_path) between 1 and 300);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'content_page_views_campaign_lengths'
      and conrelid = 'public.content_page_views'::regclass
  ) then
    alter table public.content_page_views
      add constraint content_page_views_campaign_lengths
      check (
        (utm_source is null or char_length(utm_source) <= 120)
        and (utm_medium is null or char_length(utm_medium) <= 120)
        and (utm_campaign is null or char_length(utm_campaign) <= 120)
        and (utm_content is null or char_length(utm_content) <= 120)
      );
  end if;
end $$;

create index if not exists content_page_views_visitor_time_idx
  on public.content_page_views (visitor_id, viewed_at desc)
  where visitor_id is not null;

create index if not exists content_page_views_session_time_idx
  on public.content_page_views (session_id, viewed_at desc)
  where session_id is not null;

create index if not exists content_page_views_campaign_time_idx
  on public.content_page_views (utm_source, utm_medium, utm_campaign, viewed_at desc)
  where utm_source is not null;

create table if not exists public.content_engagement_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  page_path text not null,
  language text not null default 'ko',
  visitor_id uuid not null,
  session_id uuid not null,
  event_at timestamptz not null default now(),
  constraint content_engagement_event_type check (
    event_type in ('engaged_30s', 'scroll_50', 'scroll_90', 'share_click', 'newsletter_signup')
  ),
  constraint content_engagement_path_length check (char_length(page_path) between 1 and 300),
  constraint content_engagement_language check (language in ('ko', 'en'))
);

alter table public.content_engagement_events enable row level security;
revoke all on table public.content_engagement_events from public, anon, authenticated;
revoke all on sequence public.content_engagement_events_id_seq from public, anon, authenticated;

create unique index if not exists content_engagement_session_event_uidx
  on public.content_engagement_events (session_id, page_path, event_type);

create index if not exists content_engagement_type_time_idx
  on public.content_engagement_events (event_type, event_at desc);

create index if not exists content_engagement_path_time_idx
  on public.content_engagement_events (page_path, event_at desc);

create or replace function public.record_content_view(
  p_path text,
  p_language text default 'ko',
  p_referrer_host text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_path text := left(coalesce(nullif(p_path, ''), '/'), 300);
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_referrer text := nullif(lower(left(btrim(coalesce(p_referrer_host, '')), 200)), '');
begin
  perform private.enforce_rpc_rate_limit('content_view', null, 120, 300);

  if auth.uid() is not null and public.is_seed_owner() then return; end if;
  if left(v_path, 1) <> '/' then v_path := '/'; end if;
  if v_path <> '/' then v_path := regexp_replace(v_path, '/+$', ''); end if;
  if v_path like '/account%' or v_path like '/insights%' then return; end if;

  insert into public.content_page_views (page_path, language, referrer_host)
  values (v_path, v_language, v_referrer);
end;
$$;

create or replace function public.record_content_view_v2(
  p_path text,
  p_language text,
  p_referrer_host text,
  p_visitor_id uuid,
  p_session_id uuid,
  p_entry_path text,
  p_utm_source text,
  p_utm_medium text,
  p_utm_campaign text,
  p_utm_content text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_path text := left(coalesce(nullif(p_path, ''), '/'), 300);
  v_entry_path text := left(coalesce(nullif(p_entry_path, ''), v_path), 300);
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
  v_referrer text := nullif(lower(left(btrim(coalesce(p_referrer_host, '')), 200)), '');
  v_source text := nullif(lower(left(btrim(coalesce(p_utm_source, '')), 120)), '');
  v_medium text := nullif(lower(left(btrim(coalesce(p_utm_medium, '')), 120)), '');
  v_campaign text := nullif(left(btrim(coalesce(p_utm_campaign, '')), 120), '');
  v_content text := nullif(left(btrim(coalesce(p_utm_content, '')), 120), '');
begin
  perform private.enforce_rpc_rate_limit('content_view_v2', null, 120, 300);

  if auth.uid() is not null and public.is_seed_owner() then return; end if;
  if left(v_path, 1) <> '/' then v_path := '/'; end if;
  if left(v_entry_path, 1) <> '/' then v_entry_path := '/'; end if;
  if v_path <> '/' then v_path := regexp_replace(v_path, '/+$', ''); end if;
  if v_entry_path <> '/' then v_entry_path := regexp_replace(v_entry_path, '/+$', ''); end if;
  if v_path like '/account%' or v_path like '/insights%' then return; end if;

  insert into public.content_page_views (
    page_path, language, referrer_host, visitor_id, session_id, entry_path,
    utm_source, utm_medium, utm_campaign, utm_content
  ) values (
    v_path, v_language, v_referrer, p_visitor_id, p_session_id, v_entry_path,
    v_source, v_medium, v_campaign, v_content
  );
end;
$$;

create or replace function public.record_content_event(
  p_event_type text,
  p_path text,
  p_language text,
  p_visitor_id uuid,
  p_session_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_path text := left(coalesce(nullif(p_path, ''), '/'), 300);
  v_language text := case when p_language = 'en' then 'en' else 'ko' end;
begin
  perform private.enforce_rpc_rate_limit('content_event', null, 180, 300);

  if auth.uid() is not null and public.is_seed_owner() then return; end if;
  if p_event_type not in ('engaged_30s', 'scroll_50', 'scroll_90', 'share_click', 'newsletter_signup') then
    raise exception 'invalid event type' using errcode = '22023';
  end if;
  if left(v_path, 1) <> '/' then v_path := '/'; end if;
  if v_path <> '/' then v_path := regexp_replace(v_path, '/+$', ''); end if;
  if v_path like '/account%' or v_path like '/insights%' then return; end if;

  insert into public.content_engagement_events (
    event_type, page_path, language, visitor_id, session_id
  ) values (
    p_event_type, v_path, v_language, p_visitor_id, p_session_id
  )
  on conflict (session_id, page_path, event_type) do nothing;
end;
$$;

drop function if exists public.get_engagement_summary();
create function public.get_engagement_summary()
returns table (metric text, value bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with boundary as (
      select ((now() at time zone 'Asia/Seoul')::date - 29)::timestamp at time zone 'Asia/Seoul' as start_at
    ), repeat_visitors as (
      select count(*)::bigint as total
      from (
        select v.visitor_id
        from public.content_page_views v, boundary b
        where v.viewed_at >= b.start_at and v.visitor_id is not null
        group by v.visitor_id
        having count(distinct v.session_id) >= 2
      ) visitors
    )
    select 'active_subscribers'::text, count(*)::bigint from public.newsletter_subscribers where status = 'active'
    union all select 'all_page_views', count(*)::bigint from public.content_page_views
    union all select 'page_views_today', count(*)::bigint from public.content_page_views
      where viewed_at >= (now() at time zone 'Asia/Seoul')::date::timestamp at time zone 'Asia/Seoul'
    union all select 'page_views_7d', count(*)::bigint from public.content_page_views
      where viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul'
    union all select 'page_views_30d', count(*)::bigint from public.content_page_views, boundary
      where viewed_at >= boundary.start_at
    union all select 'member_count', count(*)::bigint from auth.users where deleted_at is null
    union all select 'unique_visitors_30d', count(distinct visitor_id)::bigint
      from public.content_page_views, boundary where viewed_at >= boundary.start_at and visitor_id is not null
    union all select 'returning_visitors_30d', total from repeat_visitors
    union all select 'engaged_sessions_30d', count(distinct session_id)::bigint
      from public.content_engagement_events, boundary
      where event_at >= boundary.start_at and event_type = 'engaged_30s';
end;
$$;

drop function if exists public.get_daily_view_stats();
create function public.get_daily_view_stats()
returns table (view_date date, views bigint, visitors bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with days as (
      select generate_series(
        (now() at time zone 'Asia/Seoul')::date - 6,
        (now() at time zone 'Asia/Seoul')::date,
        interval '1 day'
      )::date as day
    ), counts as (
      select
        (v.viewed_at at time zone 'Asia/Seoul')::date as day,
        count(*)::bigint as total_views,
        count(distinct v.visitor_id)::bigint as total_visitors
      from public.content_page_views v
      where v.viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 6)::timestamp at time zone 'Asia/Seoul'
      group by 1
    )
    select d.day, coalesce(c.total_views, 0)::bigint, coalesce(c.total_visitors, 0)::bigint
    from days d left join counts c using (day)
    order by d.day;
end;
$$;

drop function if exists public.get_content_view_stats();
create function public.get_content_view_stats()
returns table (
  page_path text,
  views bigint,
  unique_visitors bigint,
  engaged_sessions bigint,
  last_viewed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with normalized_views as (
      select
        case when regexp_replace(v.page_path, '/+$', '') = '' then '/' else regexp_replace(v.page_path, '/+$', '') end as path,
        v.visitor_id,
        v.viewed_at
      from public.content_page_views v
    ), view_totals as (
      select path, count(*)::bigint as total_views,
        count(distinct visitor_id)::bigint as total_visitors, max(viewed_at) as last_at
      from normalized_views group by path
    ), engagement_totals as (
      select e.page_path as path, count(distinct e.session_id)::bigint as total_engaged
      from public.content_engagement_events e
      where e.event_type = 'engaged_30s'
      group by e.page_path
    )
    select v.path, v.total_views, v.total_visitors, coalesce(e.total_engaged, 0)::bigint, v.last_at
    from view_totals v left join engagement_totals e using (path)
    order by v.total_views desc, v.last_at desc
    limit 100;
end;
$$;

create or replace function public.get_traffic_source_stats()
returns table (source text, medium text, campaign text, views bigint, visitors bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    select
      coalesce(nullif(v.utm_source, ''), nullif(v.referrer_host, ''), 'direct')::text,
      coalesce(nullif(v.utm_medium, ''), '')::text,
      coalesce(nullif(v.utm_campaign, ''), '')::text,
      count(*)::bigint,
      count(distinct v.visitor_id)::bigint
    from public.content_page_views v
    where v.viewed_at >= ((now() at time zone 'Asia/Seoul')::date - 29)::timestamp at time zone 'Asia/Seoul'
    group by 1, 2, 3
    order by count(*) desc
    limit 50;
end;
$$;

create or replace function public.get_engagement_funnel()
returns table (stage text, total bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_seed_owner() then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  return query
    with boundary as (
      select ((now() at time zone 'Asia/Seoul')::date - 29)::timestamp at time zone 'Asia/Seoul' as start_at
    ), stages(stage, sort_order) as (
      values ('page_view'::text, 1), ('engaged_30s', 2), ('scroll_50', 3),
        ('scroll_90', 4), ('share_click', 5), ('newsletter_signup', 6)
    ), totals as (
      select 'page_view'::text as stage, count(*)::bigint as total
      from public.content_page_views, boundary
      where viewed_at >= boundary.start_at and visitor_id is not null
      union all
      select e.event_type, count(*)::bigint
      from public.content_engagement_events e, boundary
      where e.event_at >= boundary.start_at
      group by e.event_type
    )
    select s.stage, coalesce(t.total, 0)::bigint
    from stages s left join totals t using (stage)
    order by s.sort_order;
end;
$$;

revoke all on function public.record_content_view(text, text, text) from public, anon, authenticated;
revoke all on function public.record_content_view_v2(text, text, text, uuid, uuid, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.record_content_event(text, text, text, uuid, uuid) from public, anon, authenticated;
revoke all on function public.get_engagement_summary() from public, anon, authenticated;
revoke all on function public.get_daily_view_stats() from public, anon, authenticated;
revoke all on function public.get_content_view_stats() from public, anon, authenticated;
revoke all on function public.get_traffic_source_stats() from public, anon, authenticated;
revoke all on function public.get_engagement_funnel() from public, anon, authenticated;

grant execute on function public.record_content_view(text, text, text) to anon, authenticated;
grant execute on function public.record_content_view_v2(text, text, text, uuid, uuid, text, text, text, text, text) to anon, authenticated;
grant execute on function public.record_content_event(text, text, text, uuid, uuid) to anon, authenticated;
grant execute on function public.get_engagement_summary() to authenticated;
grant execute on function public.get_daily_view_stats() to authenticated;
grant execute on function public.get_content_view_stats() to authenticated;
grant execute on function public.get_traffic_source_stats() to authenticated;
grant execute on function public.get_engagement_funnel() to authenticated;
