import type { ColumnTranslation } from "../types";
export const issue55: ColumnTranslation = {
 title: "The House Was Worth More. There Was No More Money for Taxes",
 subtitle: "When Taxpaying Citizens Change Politics, Part 1 · The beginnings of America’s taxpayer movement",
 author: "Little Seed",
 summary: "A rising house price does not put more cash in a homeowner’s pocket. In California, anxiety over tax bills became more than 1.5 million signatures and a limit on property taxes. How did ordinary worries become rules that government had to follow?",
 heroImage: {alt:"Cheering supporters surround Howard Jarvis after the Proposition 13 victory",caption:"Howard Jarvis surrounded by supporters immediately after California’s property-tax initiative victory in 1978.",credit:"Mike Meadows / Los Angeles Times Photographic Collection, UCLA Library · CC BY 4.0 · Cropped to 16:9"},
 inlineImage: {alt:"President Reagan signs the Tax Reform Act of 1986 with lawmakers present",caption:"President Reagan signs the Tax Reform Act on October 22, 1986. The legislation reflected the work of the president, Congress and several organizations.",credit:"White House Photographic Office / National Archives · U.S. federal government public-domain work · Cropped to 16:9"},
 additionalImages:[{alt:"President Reagan signs the Tax Reform Act of 1986 with lawmakers present",caption:"President Reagan signs the Tax Reform Act on October 22, 1986. The legislation reflected the work of the president, Congress and several organizations.",credit:"White House Photographic Office / National Archives · U.S. federal government public-domain work · Cropped to 16:9"}],
 sections:[
 {title:"When Taxpaying Citizens Change Politics, Part 1",paragraphs:[
 "A rising house price sounds like good news. If a home bought years ago has doubled in value, surely its owner is better off?",
 "For someone who needs to keep living there, the picture can be quite different. A higher house price does not increase a monthly salary or pension. Until the house is sold, the additional wealth is a number on paper. When the tax bill rises with that number, the story changes.",
 "The house is worth more. There is less money to keep living in it.",
 "Many Californians knew that anxiety in the 1970s. Inflation and rising property prices pushed up taxes on homes. California’s tax authorities later recorded that reductions in tax rates failed to fully offset the additional revenue generated by rising values. Meanwhile, a growing state surplus intensified public frustration.[1](https://boe.ca.gov/info/pub216/index.htm)",
 "Government’s accounts grew healthier while citizens’ wallets grew thinner."
 ]},
 {title:"Would a Tax Bill Force Them Out of Their Homes?",paragraphs:[
 "Think of property tax as a percentage multiplied by a home’s assessed value. Even if the percentage stays the same, a higher assessment means a larger bill. A rise in house prices becomes a rise in taxes.",
 "For retirees, that can be especially painful. After a lifetime of work, they own a home and live on a fixed pension. Expensive sales nearby push up the assessment on their own property. What the market says their house is worth drifts away from what they can afford to pay.",
 "A later public-radio report preserved memories of that anxiety. An assessor recalled receiving calls after valuation notices went out in 1978. Residents said that after paying their property taxes, they would struggle to make their mortgage payments.[2](https://projects.scpr.org/prop-13/history/)",
 "It is easy to imagine a bill unfolded on the kitchen table, a calculator beside it. Spend less on food? Postpone another expense? What if the bill rises again next year?",
 "Howard Jarvis and Paul Gann helped turn that anxiety into a shared demand. They pushed a citizens’ initiative to limit California property taxes.[3](https://repository.uclawsf.edu/ca_ballot_props/850/)",
 "An initiative lets citizens draft a proposed change, collect signatures and, once the legal requirements are met, put it to a vote. Citizens move beyond asking legislators and waiting for an answer. They put the question on the agenda and decide it themselves.",
 "The proposal was called Proposition 13. Its name was dry. Its demand was close to everyday life: set a limit on the taxes property owners would have to bear."
 ]},
 {title:"Frustration Became Signatures. Signatures Became Rules",paragraphs:[
 "Jarvis had spent years trying to change property taxation. The initiative campaign collected signatures and made its case on radio. According to public radio’s retrospective reporting, it had gathered more than 1.5 million signatures by the end of 1977.[2](https://projects.scpr.org/prop-13/history/)",
 "One person’s tax bill can remain one person’s worry. When people with the same worry began signing, it became a demand government had to answer.",
 "On June 6, 1978, California voters approved the initiative with 64.8 percent of the vote. More than six out of ten voters put a brake on property taxes.[3](https://repository.uclawsf.edu/ca_ballot_props/850/)",
 "Two provisions lay at its heart. The basic property-tax rate was capped at 1 percent of the taxable value. While the same owner continued to hold a property, annual increases in that value were generally limited to 2 percent. Changes of ownership and new construction triggered reassessment. Additional levies for approved debt and other applicable exceptions remained separate.[4](https://www.law.cornell.edu/supremecourt/text/505/1)",
 "Put simply, voters built a fence around their bills. A surge in nearby house prices would no longer make next year’s taxes climb without that restraint.",
 "Owners could now anticipate more of the following year’s burden. For people planning to stay in their homes, that predictability mattered.",
 "A photograph taken immediately after the victory shows supporters crowding around Jarvis, cheering and holding signs aloft. Behind the percentages were people who felt they had regained a say over their own lives."
 ]},
 {title:"A Victory Still Needed People to Defend It",paragraphs:[
 "Winning a vote does not finish the work. New bills appear. Taxes acquire new names. Other charges emerge. Someone still needs to watch the legislature, explain the rules and tell citizens what is changing.",
 "Those who had worked with Jarvis saw a need for a permanent organization. The Howard Jarvis Taxpayers Association describes its beginnings in those terms: an organization to defend the property-tax limits and keep watching taxpayers’ burdens.[5](https://www.hjta.org/about-hjta/the-history-of-hjta/)",
 "The movement changed shape. Citizens who had become angry whenever a bill arrived became citizens who kept following the rules government made and revised.",
 "Lower property taxes also raised questions about funding schools, fire services and libraries. Differences in tax bills between longstanding owners and recent buyers remained contentious. Citizens’ burdens and public spending both required continued scrutiny.[2](https://projects.scpr.org/prop-13/history/)[4](https://www.law.cornell.edu/supremecourt/text/505/1)",
 "That is why a tax-watch movement has lasting work to do: examine the burden of collecting money, the need for spending it and the results it produces."
 ]},
 {title:"From California’s Anxiety to an Organization in Washington",paragraphs:[
 "America’s taxpayer movement grew through several places and organizations. In that broader setting, Americans for Tax Reform—ATR—was founded in Washington in 1985. Its founder was Grover Norquist. ATR says it was established at President Reagan’s request.[6](https://atr.org/about/)",
 "California’s initiative campaign and ATR were distinct organizations and events. The 1978 victory occurred seven years before ATR existed. Citizens first demonstrated that tax rules could be changed; a later organization worked in federal politics to promote tax cuts and oppose increases.",
 "ATR developed a distinctive method. It asked candidates to make a written promise against tax increases, published the names of signers and monitored whether they kept that promise after taking office. It called this the Taxpayer Protection Pledge.[7](https://atr.org/about-the-pledge/)",
 "Citizens gained a standard they could remember. A candidate’s words during the campaign could be connected to that person’s choices in Congress.",
 "The major tax reform enacted in 1986 brought the top individual income-tax rate down from 50 to 28 percent. ATR supported the reform. The president, Congress and several organizations all contributed to the legislation.[8](https://apps.irs.gov/app/understandingTaxes/teacher/whys_thm02_les06.jsp)[6](https://atr.org/about/)",
 "Taxation became an important subject of civic organizing in America. People asking how much they should pay, how much government could collect and whether politicians had kept their word built organizations and influenced politics."
 ]},
 {title:"At Our Own Kitchen Tables",paragraphs:[
 "The story is familiar from Korea. A house’s market price is different from a bank balance. A shop’s sales are different from the money its owner takes home. Those gaps reveal how heavily a tax can weigh on daily life.",
 "American citizens explained their burdens together, collected signatures, changed rules and left organizations to defend those rules. That process suggests a starting point for a Korean civic tax-watch movement.",
 "Start with a tax bill a citizen sends in, the money a shop actually earns or the cost of staying in a longtime home. Explain which rules increase the burden and identify rules that can be changed. Ask those responsible to answer. Keep a record of their answers and their actions.",
 "People who pay taxes have a voice with which to explain their lives. When scattered voices come together, they can become standards government must observe.",
 "In the next installment, we will unfold the pledge ATR asked politicians to sign. Where did the power to hold them to their campaign promises come from?"
 ]}
 ],
 sourceNote:"The opening household explanation and kitchen-table scene are illustrations, rather than a reconstruction of any individual’s testimony. ATR’s and HJTA’s accounts of their origins are identified as their own organizational histories. The historical photograph is licensed under CC BY 4.0; the license is linked below.",
 sourceLabels:["[1] California State Board of Equalization · Background to the 1978 tax revolt","[2] Capital Public Radio / KPCC · Residents’ memories and the signature campaign","[3] UC Law San Francisco · Proposition 13 voting record","[4] U.S. Supreme Court · Nordlinger v. Hahn (1992)","[5] Howard Jarvis Taxpayers Association · Organizational history","[6] ATR · Founding and activities (organizational account)","[7] ATR · The Taxpayer Protection Pledge","[8] IRS · The 1986 tax reform","Photo license · Creative Commons Attribution 4.0"]
};
