import { useEffect,useRef,useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth";
import { useLanguage } from "../i18n";
import { resolveDiscussionSource } from "../data/discussionSources";
import { parseCommentBody } from "../lib/comments";
import { listReplyJobs,replyAction,saveReplyJob,type ReplyJob } from "../lib/commentDesk";

const labels={pending:"초안 대기",generating:"씨야 작성 중",ready:"승인 대기",failed:"생성 실패",skipped:"답글 보류",posted:"게시 완료"};
export default function CommentDesk(){
  const {session,user,loading:authLoading}=useAuth();const {language}=useLanguage();const ko=language==="ko";
  const owner=user?.app_metadata?.seed_role==="owner";
  const [jobs,setJobs]=useState<ReplyJob[]>([]),[selected,setSelected]=useState<string|null>(null),[body,setBody]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("unread"),[offset,setOffset]=useState(0),[loading,setLoading]=useState(false);
  const alive=useRef(true);
  const current=jobs.find(j=>j.comment_id===selected);
  useEffect(()=>{if(current && !body && current.draft_body)setBody(current.edited_body || current.draft_body);},[current?.draft_body,selected]);
  const refresh=async()=>{if(!session || !owner)return;setLoading(true);try{const next=await listReplyJobs(session,offset);if(alive.current){setJobs(next);}}catch(e){if(alive.current)setNotice(e instanceof Error?e.message:"불러오기 실패");}finally{if(alive.current)setLoading(false);}};
  useEffect(()=>{alive.current=true;void refresh();const timer=window.setInterval(refresh,30000);window.addEventListener("focus",refresh);return()=>{alive.current=false;window.clearInterval(timer);window.removeEventListener("focus",refresh);};},[session?.access_token,owner,offset]);
  const choose=async(job:ReplyJob)=>{setSelected(job.comment_id);setBody(job.edited_body || job.draft_body);setNotice("");if(session && !job.seen_at){try{await saveReplyJob(session,job.comment_id,{seen_at:new Date().toISOString()});await refresh();}catch(e){setNotice(e instanceof Error?e.message:"확인 표시 실패");}}};
  const act=async(action:"save"|"publish"|"retry"|"skip")=>{if(!session || !current || busy)return;setBusy(true);setNotice("");try{
    if(action==="save")await saveReplyJob(session,current.comment_id,{edited_body:body});
    else await replyAction(session,current.comment_id,action,body);
    setNotice(action==="publish"?"씨야 답글이 게시되었습니다.":action==="save"?"수정한 초안을 저장했습니다.":action==="retry"?"초안을 다시 생성합니다. 약 1분 후 확인해주세요.":"답글을 보류했습니다.");
    await refresh();
  }catch(e){setNotice(e instanceof Error?e.message:"처리 실패");}finally{setBusy(false);}};
  const visible=jobs.filter(j=>filter==="all" || (filter==="unread"?!j.seen_at:filter==="waiting"?["pending","generating","ready","failed"].includes(j.status):j.status==="posted"));
  if(authLoading)return <p className="container-page py-20">{ko?"로그인 확인 중…":"Checking access…"}</p>;
  if(!owner)return <section className="container-page py-20"><h1 className="text-3xl font-bold">{ko?"댓글 관리":"Comment desk"}</h1><p className="mt-4">{ko?"운영자 계정으로 로그인해주세요.":"Sign in as the owner."}</p><Link className="button-primary mt-6" to="/account?returnTo=/insights/comments">{ko?"로그인":"Sign in"}</Link></section>;
  return <section className="container-page py-8"><header className="flex flex-wrap items-start justify-between gap-4 border-b-2 border-navy pb-5"><div><h1 className="text-3xl font-extrabold text-navy">{ko?"댓글·씨야 답글 관리":"Comments & Siya replies"}</h1><p className="mt-3 text-sm leading-6 text-charcoal/65">{ko?"모든 기사 댓글을 한곳에서 확인합니다. 씨야 초안은 공개되지 않으며, 수정 후 ‘승인하고 게시’를 눌러야 답글이 등록됩니다.":"Review all article comments here. Siya drafts stay private until you approve and publish."}</p><p className="mt-2 text-xs text-charcoal/50">{ko?"30초마다 새 댓글 확인 · 자동 초안은 약 1분 후 생성 · 사이트 댓글만 수집":"Checks every 30 seconds · drafts generated after about a minute · website comments only"}</p></div><button onClick={()=>void refresh()} disabled={loading} className="button-secondary">{ko?"새 댓글 확인":"Refresh"}</button></header>
    <div className="mt-5 flex flex-wrap gap-2">{[["unread","미확인"],["waiting","답글 처리 대기"],["posted","게시 완료"],["all","전체"]].map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`rounded-full border px-4 py-2 text-sm font-bold ${filter===key?"bg-green-deep text-white":"bg-white text-green-deep"}`}>{label} {jobs.filter(j=>key==="all" || (key==="unread"?!j.seen_at:key==="waiting"?["pending","generating","ready","failed"].includes(j.status):j.status==="posted")).length}</button>)}</div>
    {notice && <p role="status" className="mt-4 rounded-lg bg-green-pale p-4 text-sm">{notice}</p>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(260px,0.8fr)_minmax(0,1.4fr)]"><aside className="space-y-3">{visible.map(j=>{const s=resolveDiscussionSource(j.comments.post_slug);return <button key={j.comment_id} onClick={()=>void choose(j)} className={`w-full rounded-lg border bg-white p-4 text-left ${selected===j.comment_id?"border-green-deep ring-1 ring-green-deep":"border-green-deep/15"}`}><span className="text-xs font-bold text-green-mid">{!j.seen_at?"● 새 댓글 · ":""}{labels[j.status]}</span><strong className="mt-2 block text-sm text-navy">{s.title}</strong><p className="mt-2 text-xs text-charcoal/50">{j.comments.nickname} · {new Date(j.comments.created_at).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}</p><p className="mt-2 line-clamp-3 text-sm leading-6">{parseCommentBody(j.comments.body).text}</p></button>;})}{!loading && !visible.length && <p className="rounded-lg border bg-white p-8 text-sm">해당 댓글이 없습니다.</p>}<div className="flex justify-between"><button disabled={offset===0} className="button-secondary" onClick={()=>{setOffset(Math.max(0,offset-100));setSelected(null);}}>이전</button><button disabled={jobs.length<100} className="button-secondary" onClick={()=>{setOffset(offset+100);setSelected(null);}}>다음</button></div></aside>
    <div>{current?<article className="rounded-xl border border-green-deep/15 bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><h2 className="font-extrabold">{current.comments.nickname}님의 댓글</h2><Link to={`${current.article_path || resolveDiscussionSource(current.comments.post_slug).path}#comments`} className="text-sm font-bold text-green-deep">기사·댓글 보기 ↗</Link></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{parseCommentBody(current.comments.body).text}</p><p className="mt-4 text-xs font-bold text-green-mid">{labels[current.status]}</p>{current.core_concern && <p className="mt-2 rounded-md bg-green-pale p-3 text-sm">독자의 핵심 의견: {current.core_concern}</p>}{current.error && <p className="mt-3 text-sm text-red-700">{current.error}</p>}
      {current.article_snapshot && <details className="mt-4 border-y py-3"><summary className="cursor-pointer text-sm font-bold">초안이 참고한 기사 본문 · {current.article_title}</summary><p className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-sm leading-7">{current.article_snapshot}</p></details>}
      <label className="mt-5 block text-sm font-bold">{current.status==="posted"?"게시된 씨야 답글":"씨야 답글 초안 · 자유롭게 수정"}<textarea className="mt-3 min-h-56 w-full rounded-lg border border-green-deep/20 p-4 text-sm font-normal leading-7" value={body} onChange={e=>setBody(e.target.value)} maxLength={800} disabled={current.status==="posted" || busy} /></label><p className="mt-2 text-xs text-charcoal/45">{body.length}/800자 · AI 씨야 답글로 표시됩니다.</p>
      {current.status!=="posted" && <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy || body.trim().length<2 || current.status==="generating"} className="button-primary disabled:opacity-40" onClick={()=>void act("publish")}>승인하고 게시</button><button disabled={busy} className="button-secondary" onClick={()=>void act("save")}>초안 저장</button><button disabled={busy || current.status==="generating"} className="button-secondary" onClick={()=>void act("retry")}>다시 생성</button><button disabled={busy} className="button-secondary" onClick={()=>void act("skip")}>답글 보류</button></div>}
    </article>:<div className="rounded-xl border border-dashed border-green-deep/25 p-10 text-center text-sm text-charcoal/60">댓글을 선택하면 기사와 답글 초안을 확인할 수 있습니다.</div>}</div></div>
  </section>;
}
